.PHONY: clean All

All:
	@echo "----------Building project:[ EX2 - Debug ]----------"
	@cd "EX2" && "$(MAKE)" -f  "EX2.mk"
clean:
	@echo "----------Cleaning project:[ EX2 - Debug ]----------"
	@cd "EX2" && "$(MAKE)" -f  "EX2.mk" clean
