.PHONY: clean All

All:
	@echo "----------Building project:[ Ex2Stero - Debug ]----------"
	@cd "Ex2Stero" && "$(MAKE)" -f  "Ex2Stero.mk"
clean:
	@echo "----------Cleaning project:[ Ex2Stero - Debug ]----------"
	@cd "Ex2Stero" && "$(MAKE)" -f  "Ex2Stero.mk" clean
